const englishStrings = {
    welcome_to_appendre:'Welcome to Appendre',
    about_appendre:'The world\'s foremost French Learning Pen Pal Sight',
    login: 'Login',
    logout: 'Logout',
    username: 'username',
    password: 'password',
    signup: 'signup',
    continue_as_guest: 'Continue as guest',
    profile: 'Profile',
    trending_letters: 'Trending Letters',
    trending_replies: 'Trending Replies',
    french: 'Français',
    english: 'English',
    collaborators: 'Collaborators',
    myLetters: 'My Letters',
    writeALetter: 'Write a Letter',
    whatDoYouWantToSay: 'What do you want to say',
    title: 'Title',
    add: 'Add',
    letter: 'letter',
    tags: 'Tags',
    by: 'By',
    likes: 'Likes',
    dislikes: 'Dislikes',
    postedOn: 'Posted On',
    post: 'Poster'
};

export default englishStrings;