const frenchStrings = {
    welcome_to_appendre:'Bienvenue À Appendre',
    about_appendre:'La principal site web de l\'apprentisage de Francais par les correspondants',
    login: 'Se Connecter',
    logout: 'Se Déconnecter',
    username: 'Identifiant',
    password: 'Mot de Passe',
    signup: 'Enregistrer',
    continue_as_guest: 'Continue sans se Connecter',
    profile: 'Profile',
    trending_letters: 'Lettres Populaire',
    trending_replies: 'Reponse Populaire',
    french: 'Français',
    english: 'English',
    collaborators: 'Collaborateurs',
    myLetters: 'Mes Documents',
    writeALetter: "Ecrit une Lettre",
    whatDoYouWantToSay: 'Ce Que Vous-Voulez Dire',
    title: 'Titre',
    add: 'Ajouter',
    letter: 'Lettre',
    tags: 'Étiquettes',
    by: 'Par',
    likes: 'J\'aime',
    dislikes: 'Détester',
    postedOn: 'Publié á',
    post: 'Poster'
};

export default frenchStrings;